# Site settings
baseurl = "https://hjdskes.nl/"
theme = "diego"
languageCode = "en-us"
author = "Jente Hidskes"
title = "Jente Hidskes' website"
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
dateform = "Jan 2, 2006"
description = "Jente Hidskes' website"
copyright = "Copyright © 2016-2018 Jente Hidskes"
logofile = "img/avatar.png"
latestpostcount = 5
github = "Hjdskes"
email = "hjdskes@gmail.com"
