# Site settings
baseurl = "https://www.hjdskes.nl/"
theme = "diego"
languageCode = "en-us"
title = "Jente Hidskes' website"
copyright = "Copyright © 2016-2022 Jente Hidskes"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true

[author]
  name = "Jente Hidskes"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
dateform = "Jan 2, 2006"
description = "Jente Hidskes' website"
logofile = "img/avatar.svg"
latestpostcount = 5
github = "Hjdskes"
twitter = "Hjdskes"
gnome = "Hjdskes"
email = "personal@hjdskes.nl"

[frontmatter]
lastmod = [":git", "lastmod", "date", "publishDate"]
