name = "Cactus Hjdskes"
license = "MIT"
licenselink = "https://github.com/Hjdskes/hjdskes.github.io/blob/master/themes/cactus-hjdskes/LICENSE.md"
description = "An adaptation of the Cactus theme for Hugo"
homepage = ""
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Jente Hidskes"
  homepage = "https://hjdskes.github.io"

[original]
  name = "digitalcraftsman"
  homepage = "http://themes.gohugo.io/theme/cactus/"
  repo = "https://github.com/digitalcraftsman/hugo-cactus-theme"
